apiVersion: v1
kind: ConfigMap
metadata:
  name: static-targets-config
  labels:
    {{- include "auto-passport.labels" . | nindent 4 }}
data:
  config.yaml: |
    static_targets:
      airflow:
        - https://airflow-vtz.dns-shop.ru
      metabase:
        - https://metabase-dev.dns-shop.ru
      superset:
        - https://superset-dev.dns-shop.ru