apiVersion: v1
kind: ConfigMap
metadata:
  name: static-targets-config
  labels:
    {{- include "auto-passport.labels" . | nindent 4 }}
data:
  config.yaml: |
    static_targets:
      airflow:
        - airflow-vtz.dns-shop.ru
        - airflow-tpz-dev.dns-shop.ru
      metabase:
        - metabase-dev.dns-shop.ru
      superset:
        - superset-dev.dns-shop.ru
    cluster: airflow-sph-dev
    api_endpoint: http://10.10.243.53:8080